project_id = "hepscjgcjnlofdpoewqx"

[functions.fetch-youtube-analytics]
verify_jwt = false

[functions.fetch-instagram-analytics]
verify_jwt = false

[functions.fetch-tiktok-analytics]
verify_jwt = false

[functions.refresh-campaign-analytics]
verify_jwt = false

[functions.refresh-campaigns-with-progress]
verify_jwt = false

[functions.send-milestone-celebration]
verify_jwt = false
