project_id = "hepscjgcjnlofdpoewqx"

[functions.youtube-oauth-initiate]
verify_jwt = false

[functions.youtube-oauth-callback]
verify_jwt = false

[functions.youtube-refresh-token]
verify_jwt = false

[functions.youtube-get-channel-info]
verify_jwt = false

[functions.youtube-get-video-list]
verify_jwt = false

[functions.youtube-get-video-retention]
verify_jwt = false

[functions.fetch-youtube-analytics]
verify_jwt = false

[functions.fetch-instagram-analytics]
verify_jwt = false

[functions.fetch-tiktok-analytics]
verify_jwt = false

[functions.refresh-campaign-analytics]
verify_jwt = false

[functions.refresh-campaigns-with-progress]
verify_jwt = false

[functions.send-milestone-celebration]
verify_jwt = false

[functions.scheduled-daily-refresh]
verify_jwt = false

[functions.analyze-campaign-sentiment]
verify_jwt = false
